//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMT_D.o.T_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_ProcessRoleUser_Detail
    {
        public int id { get; set; }
        public int process_role_id { get; set; }
        public int users_id { get; set; }
        public int running_process_detail_id { get; set; }
    
        public virtual APMT_Process_Role APMT_Process_Role { get; set; }
        public virtual APMT_Users APMT_Users { get; set; }
    }
}
