//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMT_D.o.T_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Running_Process_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APMT_Running_Process_Detail()
        {
            this.APMT_Timeline = new HashSet<APMT_Timeline>();
        }
    
        public int id { get; set; }
        public int process_id { get; set; }
        public int leader_id { get; set; }
        public System.DateTime targetdate { get; set; }
        public int project_id { get; set; }
    
        public virtual APMT_Project APMT_Project { get; set; }
        public virtual APMT_Users APMT_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Timeline> APMT_Timeline { get; set; }
    }
}
