//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMT_D.o.T_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Company_Member
    {
        public int id { get; set; }
        public int users_id { get; set; }
        public int company_id { get; set; }
        public int Company_Role_Id { get; set; }
    
        public virtual APMT_Company APMT_Company { get; set; }
        public virtual APMT_Users APMT_Users { get; set; }
    }
}
