//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMT_D.o.T_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APMT_Users()
        {
            this.APMT_Company_Member = new HashSet<APMT_Company_Member>();
            this.APMT_Process = new HashSet<APMT_Process>();
            this.APMT_ProcessRoleUser_Detail = new HashSet<APMT_ProcessRoleUser_Detail>();
            this.APMT_Project = new HashSet<APMT_Project>();
            this.APMT_Running_Activity_Detail = new HashSet<APMT_Running_Activity_Detail>();
            this.APMT_Running_Process_Detail = new HashSet<APMT_Running_Process_Detail>();
        }
    
        public int id { get; set; }
        public string Email { get; set; }
        public string Passwords { get; set; }
        public string FullName { get; set; }
        public string Statuss { get; set; }
        public Nullable<int> IDRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Company_Member> APMT_Company_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Process> APMT_Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_ProcessRoleUser_Detail> APMT_ProcessRoleUser_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Project> APMT_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Running_Activity_Detail> APMT_Running_Activity_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Running_Process_Detail> APMT_Running_Process_Detail { get; set; }
        public virtual Company_Role Company_Role { get; set; }
    }
}
