//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMT_D.o.T_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APMT_Step()
        {
            this.APMT_Activity = new HashSet<APMT_Activity>();
            this.APMT_Step_Input = new HashSet<APMT_Step_Input>();
            this.APMT_Step_Output = new HashSet<APMT_Step_Output>();
            this.APMT_Step_Role = new HashSet<APMT_Step_Role>();
            this.APMT_Step_To_Step = new HashSet<APMT_Step_To_Step>();
            this.APMT_Step_To_Step1 = new HashSet<APMT_Step_To_Step>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string descriptions { get; set; }
        public int process_id { get; set; }
        public int weights { get; set; }
        public string typess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Activity> APMT_Activity { get; set; }
        public virtual APMT_Process APMT_Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Step_Input> APMT_Step_Input { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Step_Output> APMT_Step_Output { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Step_Role> APMT_Step_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Step_To_Step> APMT_Step_To_Step { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Step_To_Step> APMT_Step_To_Step1 { get; set; }
    }
}
