//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMT_D.o.T_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APMT_Files()
        {
            this.APMT_Activity = new HashSet<APMT_Activity>();
            this.APMT_Running_OutputActivity_upload = new HashSet<APMT_Running_OutputActivity_upload>();
            this.APMT_Running_Step_Input = new HashSet<APMT_Running_Step_Input>();
            this.APMT_Running_Step_Output = new HashSet<APMT_Running_Step_Output>();
            this.APMT_Step_Input = new HashSet<APMT_Step_Input>();
            this.APMT_Step_Output = new HashSet<APMT_Step_Output>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool isdeliverable { get; set; }
        public int process_id { get; set; }
        public string descriptions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Activity> APMT_Activity { get; set; }
        public virtual APMT_Process APMT_Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Running_OutputActivity_upload> APMT_Running_OutputActivity_upload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Running_Step_Input> APMT_Running_Step_Input { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Running_Step_Output> APMT_Running_Step_Output { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Step_Input> APMT_Step_Input { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Step_Output> APMT_Step_Output { get; set; }
    }
}
