//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMT_D.o.T_Team.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoT_APMT_DatabaseEntities : DbContext
    {
        public DoT_APMT_DatabaseEntities()
            : base("name=DoT_APMT_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APMT_Activity> APMT_Activity { get; set; }
        public virtual DbSet<APMT_Activity_Status> APMT_Activity_Status { get; set; }
        public virtual DbSet<APMT_Comment> APMT_Comment { get; set; }
        public virtual DbSet<APMT_Company> APMT_Company { get; set; }
        public virtual DbSet<APMT_Company_Member> APMT_Company_Member { get; set; }
        public virtual DbSet<APMT_Files> APMT_Files { get; set; }
        public virtual DbSet<APMT_Process> APMT_Process { get; set; }
        public virtual DbSet<APMT_Process_Role> APMT_Process_Role { get; set; }
        public virtual DbSet<APMT_ProcessRoleUser_Detail> APMT_ProcessRoleUser_Detail { get; set; }
        public virtual DbSet<APMT_Project> APMT_Project { get; set; }
        public virtual DbSet<APMT_Running_Activity_Detail> APMT_Running_Activity_Detail { get; set; }
        public virtual DbSet<APMT_Running_OutputActivity_refer> APMT_Running_OutputActivity_refer { get; set; }
        public virtual DbSet<APMT_Running_OutputActivity_text> APMT_Running_OutputActivity_text { get; set; }
        public virtual DbSet<APMT_Running_OutputActivity_upload> APMT_Running_OutputActivity_upload { get; set; }
        public virtual DbSet<APMT_Running_Process_Detail> APMT_Running_Process_Detail { get; set; }
        public virtual DbSet<APMT_Running_Step_Detail> APMT_Running_Step_Detail { get; set; }
        public virtual DbSet<APMT_Running_Step_Input> APMT_Running_Step_Input { get; set; }
        public virtual DbSet<APMT_Running_Step_Output> APMT_Running_Step_Output { get; set; }
        public virtual DbSet<APMT_Step> APMT_Step { get; set; }
        public virtual DbSet<APMT_Step_Input> APMT_Step_Input { get; set; }
        public virtual DbSet<APMT_Step_Output> APMT_Step_Output { get; set; }
        public virtual DbSet<APMT_Step_Role> APMT_Step_Role { get; set; }
        public virtual DbSet<APMT_Step_To_Step> APMT_Step_To_Step { get; set; }
        public virtual DbSet<APMT_Timeline> APMT_Timeline { get; set; }
        public virtual DbSet<APMT_Type_Output> APMT_Type_Output { get; set; }
        public virtual DbSet<APMT_User_Company> APMT_User_Company { get; set; }
        public virtual DbSet<APMT_Users> APMT_Users { get; set; }
        public virtual DbSet<Company_Role> Company_Role { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
